# Generated by Django 4.1.1 on 2022-10-10 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_anime_list_anime_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='anime_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.anime'),
        ),
    ]
