# Generated by Django 4.1.1 on 2022-10-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_anime_user_profile_anime_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='anime_list',
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
