# Generated by Django 4.1.1 on 2022-10-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_aniem_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='aniem_list',
            new_name='anime_list',
        ),
    ]
