# Generated by Django 4.1.1 on 2022-10-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0010_remove_anime_anime_list'),
        ('users', '0011_remove_profile_anime_list_profile_anime_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='anime_list',
        ),
        migrations.AddField(
            model_name='profile',
            name='anime_list',
            field=models.ManyToManyField(to='recommendation.anime'),
        ),
    ]
