# Generated by Django 4.1.1 on 2023-12-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0015_remove_anime_profile'),
        ('users', '0013_remove_profile_anime_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='anime_list',
            field=models.ManyToManyField(to='recommendation.anime'),
        ),
    ]
