# Generated by Django 4.1.1 on 2022-10-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('anime_type', models.CharField(max_length=10)),
                ('episodes', models.IntegerField()),
                ('status', models.CharField(max_length=15)),
                ('aired', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='anime_thumbnail')),
                ('synopsis', models.TextField()),
                ('rating', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('genres', models.CharField(max_length=255)),
            ],
        ),
    ]
