# Generated by Django 4.1.1 on 2022-10-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_alter_anime_episodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
