# Generated by Django 4.1.1 on 2022-10-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_anime_list'),
        ('recommendation', '0008_alter_anime_anime_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_list',
            field=models.ManyToManyField(null=True, to='users.profile'),
        ),
    ]
