# Generated by Django 4.1.1 on 2022-10-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0009_alter_anime_anime_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='anime_list',
        ),
    ]
