# Generated by Django 4.1.1 on 2022-10-30 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_profile_anime_list'),
        ('recommendation', '0010_remove_anime_anime_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
