# Generated by Django 4.1.1 on 2023-12-27 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_profile_anime_list'),
        ('recommendation', '0012_alter_anime_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
