# Generated by Django 4.1.1 on 2023-12-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0014_alter_anime_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='profile',
        ),
    ]
